### ISSUE TITLE
Broken documentation links 

### ISSUE THREAD

**Issue by ashrosewood** [WGLab/UROBORUS#12]
Hi, 

Your documentation links are broken for this repo http://uroborus.openbioinformatics.org and [xiaofengsong/UROBORUS](https://github.com/xiaofengsong/UROBORUS) http://bioinfo.nuaa.edu.cn/uroborus.html. 

Thanks

**Comment by kaichop** [comment]
You can check documentation here
https://github.com/WGLab/UROBORUS/blob/master/docs/index.md

**Comment by ashrosewood** [comment]
Thanks, just wanted to let you know.
