### ISSUE TITLE
Is bowtie or bowtie2 being used?

### ISSUE THREAD

**Issue by linatbeishan** [WGLab/UROBORUS#3]
Hi, Kai.
  After reading the source code, I am kind of confused at the Bowtie software being used: is bowtie or bowtie2 being used?
  In tophat(v2.1.1), it will default choose bowtie2 unless you specify the --bowtie1 option; and in line 63 of your code, there is no such option specified, so I assume it's bowtie2, and provide the bowtie2 version of genome index to run by the -index option;
  But in line 96, you use the *\* bowtie*\* command, which isn't bowtie2 but with the same genome index provided through the  -index option, and  it failed to run;
  Could you kindly clarify this? Or you provided both the bowtie2 and bowtie genome index in the same path?

Thanks!
linwei

**Comment by xiaofengsong** [comment]
Thanks linwei for pointing the bug, I have updated UROBORUS.pl. Pl use new version.

**Comment by linatbeishan** [comment]
Thanks, xiaofeng.
so I think maybe you need to add the --bowtie1 option to the tophat run example in UROBORUS documentation  as well:
http://uroborus.openbioinformatics.org/en/latest/#reference

linwei
